version: '3.3'
services: 
  auth.nginx.mock:
    container_name: auth.nginx.mock
    build:
      context: .
      dockerfile: ./docker/auth.nginx.mock/Dockerfile
    expose:
        - 80
    networks:
      dehia:
        aliases:
          - auth.nginx.mock

  define.nginx.mock:
    container_name: define.nginx.mock
    build:
      context: .
      dockerfile: ./docker/define.nginx.mock/Dockerfile
    expose:
        - 80
    ports:
      - "82:80"
    networks:
      dehia:
        aliases:
          - define.nginx.mock
networks:
  dehia:
    external: true